language: node_js
node_js:
  - "8"
  - "6"
sudo: required 
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
install: 
  - sudo apt-get install nodejs
  - npm install forever
  - npm install --save discord.js
script:
  - eslint src *.js
